# -*- coding: utf-8 -*-
"""ArgilaBueno.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SnOdaM-kOCgWQSlUkyRQDzQAF7_ID48D
"""

!pip install datasets -Uq

!pip install argilla streamlit -Uq

import streamlit as st
import argilla as rg
from datetime import datetime


rg.Argilla(
    api_url=r"https://bdlse-lse-dudas.hf.space/",
    api_key= #ourKey
)

settings = rg.Settings(
    guidelines="Para cada vídeo hay que especificar de qué letra se trata y si está bien o mal signada.",
    fields=[
        rg.CustomField(
            name="video",
            template = "<video controls><source width=\"640\" height=\"500\" src={{record.fields.video.url}} type=\"video/mp4\"> Tu navegador no soporta vídeo HTML5.</video>",

        ),
    ],
    questions=[
        rg.LabelQuestion(
            name="¿Correcto?",
            labels=["Correcto","Incorrecto"]),
        rg.MultiLabelQuestion(
            name="Signo",
        labels = ["A", "Buenos días", "CH", "E", "G","H", "I", "J", "X"]),
    rg.TextQuestion(name="Observaciones", required=False)
    ]
)

dataset = rg.Dataset(
    name="video_classification_dataset",
    settings=settings,
)
dataset.create()

# Aquí están los primeros 16 vídeos que vamos a pasar a Natalia. Si se quieren añadir más se puede en otra celda

dataset.records.log([
    rg.Record(
        fields={
            "video": {
                "url": "https://unirioja-my.sharepoint.com/:v:/g/personal/magarcd_unirioja_es/ESZ3nsDeJ5tPjOrRURpqkNQBKjXFcsHQUb6tNVp-vQU2-w?nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&download=1",
            }
        }
    ),rg.Record(
        fields={
            "video": {
                "url": "https://unirioja-my.sharepoint.com/:v:/g/personal/magarcd_unirioja_es/EX8VDCk5S6hNk6Gm0hhpWSIBmp8oALiKVrRChYwd0f1RlA?nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&download=1",
            }
        }
    ),rg.Record(
        fields={
            "video": {
                "url": "https://unirioja-my.sharepoint.com/:v:/g/personal/magarcd_unirioja_es/ESyyMJJfMjlGhmmHwFVkS6sB4F803IkrJA8uGT9ByQkHag?nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&download=1",
            }
        }
    ),rg.Record(
        fields={
            "video": {
                "url": "https://unirioja-my.sharepoint.com/:v:/g/personal/magarcd_unirioja_es/EUUsTGfgGHpLkBPpHxp1qvMBv7zjtAwXQDGGx_S6ELNoyQ?nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&download=1",
            }
        }
    ),rg.Record(
        fields={
            "video": {
                "url": "https://unirioja-my.sharepoint.com/:v:/g/personal/magarcd_unirioja_es/EWuJY3u4HgxOv1d_ctxoDrQBIK_lu76ha0CFMk5oM6UZfA?nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&download=1",
            }
        }
    ),rg.Record(
        fields={
            "video": {
                "url": "https://unirioja-my.sharepoint.com/:v:/g/personal/magarcd_unirioja_es/EeBFws-XSHZArlvImU16YfIB5rWnBetkiTZlsFq2hbu0yQ?nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&download=1",
            }
        }
    ),rg.Record(
        fields={
            "video": {
                "url": "https://unirioja-my.sharepoint.com/:v:/g/personal/magarcd_unirioja_es/ES0HdEqmC7FLo-noTyfpXosBC6ux9sDnQY5Q9mEqDw16jw?nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&download=1",
            }
        }
    ),rg.Record(
        fields={
            "video": {
                "url": "https://unirioja-my.sharepoint.com/:v:/g/personal/magarcd_unirioja_es/EXgjFyZS5eFKmzfRZW4lShgBbgTOB45QXAutMATQI6SC_A?nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&download=1",
            }
        }
    ),rg.Record(
        fields={
            "video": {
                "url": "https://unirioja-my.sharepoint.com/:v:/g/personal/magarcd_unirioja_es/EUa7-lFx0hREoFWptmpPyN8BvyZ18bTW2yQQr7i_R9WQlw?nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&e=UP5419&download=1",
            }
        }
    ),rg.Record(
        fields={
            "video": {
                "url": "https://unirioja-my.sharepoint.com/:v:/g/personal/magarcd_unirioja_es/EX86G7Im8y5KuIcrKqxjBjQByAvJCA6LRGELQl4J3cu0og?nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&download=1",
            }
        }
    ),rg.Record(
        fields={
            "video": {
                "url": "https://unirioja-my.sharepoint.com/:v:/g/personal/magarcd_unirioja_es/EYqhG8hhSuRJvWOqrcRnqJIBWkt57RrG2XxTeOPIBwnIcw?nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&download=1",
            }
        }
    ),rg.Record(
        fields={
            "video": {
                "url": "https://unirioja-my.sharepoint.com/:v:/g/personal/magarcd_unirioja_es/EUQMz3VnNIREtNUdWIIDLLgBPtEiMst1l-XR_HFgBEAZHw?nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&download=1",
            }
        }
    ),rg.Record(
        fields={
            "video": {
                "url": "https://unirioja-my.sharepoint.com/:v:/g/personal/magarcd_unirioja_es/EdkiXMOtGI9Nll1FhIKHHKsBZc7-UtPJm9XYnz5tV8FH0w?nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&download=1",
            }
        }
    ),rg.Record(
        fields={
            "video": {
                "url": "https://unirioja-my.sharepoint.com/:v:/g/personal/magarcd_unirioja_es/ETdoTUmPkTlBt-mitBg_wr8BPJZw5iMvAgEiYN9JZNCJLQ?nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&download=1",
            }
        }
    ),rg.Record(
        fields={
            "video": {
                "url": "https://unirioja-my.sharepoint.com/:v:/g/personal/magarcd_unirioja_es/EST3yDDZaO1FlAqQZvg-vT8BleKhgbq6lpfD0iOyBtUxeg?nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&download=1",
            }
        }
    ),rg.Record(
        fields={
            "video": {
                "url": "https://unirioja-my.sharepoint.com/:v:/g/personal/magarcd_unirioja_es/ERxy6UxVzU9Ggo20b5uqmn8BSPSvIKm-fDbZibNVwkATpA?nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&download=1",
            }
        }
    ),]
)

# Esto es por si hace falta añadir más vídeos luego

dataset.records.log([
    rg.Record(
        fields={
            "video": {
                "url": "https://unirioja-my.sharepoint.com/:v:/g/personal/magarcd_unirioja_es/EecTfLjjInNDk_fcVylAlG4BfzW_lZYW04IDdliMYm7sKA?nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&download=1",
            }
        }
    ),rg.Record(
        fields={
            "video": {
                "url": "https://unirioja-my.sharepoint.com/:v:/g/personal/magarcd_unirioja_es/EUuETsbzBk1OgW9mQr1EcR0B1FkQI3oM7DnxFhJ5On5yhA?nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&download=1",
            }
        }
    )]
)

